[package]
name = "fastnes"
version = "0.1.0"
edition = "2021"

[lib]
name = "fastnes"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concat-idents = "1.1.5"
enumset = "1.0.12"
